name: Build & Release (Windows)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-win:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: apps/desktop

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: apps/desktop/package-lock.json

      - name: Install
        run: npm ci

      - name: Ensure ip-config.json exists
        shell: bash
        run: |
          mkdir -p electron
          [ -f electron/ip-config.json ] || echo '{}' > electron/ip-config.json

<<<<<<< HEAD
      # İstersen kaldırabilirsin; electron-builder 'install-app-deps' de yeterli olur.
      - name: Rebuild native modules
        run: npx electron-rebuild -f -w better-sqlite3

=======
>>>>>>> ac24ce1 (ci: clean workflow (no PAT), use GITHUB_TOKEN; add ensure ip-config.json)
      - name: Build & Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --win --publish always
