name: Build & Release (Windows)

on:
  push:
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-win:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: apps/desktop

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # tag bilgisi için

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # NPM optional dependency (rollup native) bug'ı için kilit dosyasını CI'da kaldır
      - name: Remove lockfile (CI-only workaround)
        run: |
          if exist package-lock.json del package-lock.json

      - name: Install deps
        run: npm install

      - name: Ensure ip-config.json exists
        shell: bash
        run: |
          mkdir -p electron
          [ -f electron/ip-config.json ] || echo '{}' > electron/ip-config.json

      - name: Build renderer
        run: npm run build:renderer

      - name: Build & Publish (GitHub Release)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --win --publish always

      - name: List release folder
        shell: bash
        run: ls -lah release || true

      # Eğer Release yüklenmezse, en azından Actions Artifacts olarak .exe gelsin
      - name: Upload EXE as Actions artifact (fallback)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: emr-pos-windows-installer
          path: apps/desktop/release/*.exe
          if-no-files-found: warn
